[package]
name = "libkeyfinder-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
pkg-config = "0.3.32"

[lib]
crate-type = ["cdylib", "rlib"]
